//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LODConvert.rc
//
#define IDS_LOD_OPEN                    1
#define IDS_DXM_SAVE                    2
#define IDS_DDS_OPEN                    3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TOOLS                       101
#define IDD_LODCONVERTEX_DIALOG         102
#define IDP_OLE_INIT_FAILED             104
#define IDD_INPUTBOX                    107
#define IDD_SELMODEWINDOW               108
#define IDD_SURFACEEDIT                 109
#define IDD_SWITCHPANEL                 110
#define IDD_TREEPANEL                   111
#define IDD_DOFEDITING                  112
#define IDD_SUNEDITING                  113
#define IDD_TEXTUREEDIT                 114
#define IDD_TEXSELECT                   115
#define IDD_3DSIMPORT                   116
#define IDD_PROGRESSBAR                 117
#define IDD_LIGHTEDIT                   118
#define IDR_MAINFRAME                   128
#define IDD_DXL_STRUCTURE               129
#define IDR_LODConvertTYPE              130
#define IDI_SURFACE                     131
#define IDI_TEXTURE                     132
#define IDI_GENERAL                     133
#define IDI_HEADER                      134
#define IDI_ROOT                        135
#define IDI_DOF                         136
#define IDI_ENDDOF                      137
#define IDI_NODE                        138
#define IDD_TOOLX                       145
#define IDD_VERTEXEDIT                  148
#define IDB_TREEBITMAP                  149
#define IDR_DOFMENU                     151
#define IDC_ENCODER_INPUT_EDIT          1000
#define IDC_ENCODER_INPUT_CHOOSE_BTN    1002
#define IDC_ENCODE                      1003
#define IDC_ENCODER_OUTPUT_EDIT         1004
#define IDC_ENCODER_OUTPUT_CHOOSE_BTN   1005
#define IDC_DECODER_EDIT                1006
#define IDC_DXL_TREE                    1007
#define IDC_SURFACE_STATIC              1008
#define IDC_SUNAMBIENT                  1008
#define IDC_DECODER_INPUT_CHOOSE_BTN    1009
#define IDC_TEXTURE_STATIC              1009
#define IDC_SUNSPECULAR                 1009
#define IDC_DECODE                      1010
#define IDC_DOF_STATIC                  1010
#define IDC_FILESIZE_STATIC             1011
#define IDC_VERTEX_NUMBER_STATIC        1012
#define IDC_DXLIST                      1013
#define IDC_LODLIST                     1014
#define IDC_LODLIST2                    1015
#define IDC_DXLIST2                     1016
#define IDC_DOFLIST                     1018
#define IDC_DOFROT                      1019
#define IDC_DOFTRANS                    1020
#define IDC_SWLIST                      1021
#define IDC_SWVALUE                     1022
#define IDC_SWTEXT                      1023
#define IDC_DISABLECHECK                1025
#define IDC_SWONBUTTON                  1026
#define IDC_FRAMESURACE                 1026
#define IDC_SWOFFBUTTON2                1027
#define IDC_DOFZERO                     1028
#define IDC_ALPHASLIDE                  1029
#define IDC_REDSLIDE                    1030
#define IDC_GREENDSLIDE                 1031
#define IDC_BLUESLIDE                   1032
#define IDC_LDIFFUSE                    1034
#define IDC_LSPECULAR                   1035
#define IDC_LAMBIENT                    1036
#define IDC_VALUES                      1037
#define IDC_MDIFFUSE                    1038
#define IDC_MSPECULAR                   1039
#define IDC_MAMBIENT                    1040
#define IDC_MEMISSIVE                   1041
#define IDC_DiscoCheck                  1042
#define IDC_DiscoCheck2                 1043
#define IDC_FogCheck                    1043
#define IDC_REFRESHVB                   1043
#define IDC_FLIPV                       1043
#define IDC_VBLIST                      1044
#define IDC_NVG                         1044
#define IDC_CONVTEXT                    1045
#define IDC_CONVPROGRESS                1046
#define IDC_NEXTKEY                     1048
#define IDC_PREVKEY                     1049
#define IDC_GOTO                        1050
#define IDC_GOTOVAL                     1051
#define IDC_DBALL                       1052
#define IDC_EXIT                        1053
#define IDC_FRAGDB                      1054
#define IDC_FRAGDB2                     1055
#define IDC_MAKEDB                      1055
#define Input                           1055
#define Message                         1056
#define IDC_COMVCHECK                   1057
#define IDC_SAMETCHECK                  1058
#define IDC_SMAVEACHECK                 1059
#define IDC_SAMEDCHECK                  1060
#define IDC_SAMESCHECK                  1061
#define IDC_SAMERCHECK                  1062
#define IDC_DIFFUSECOLOR                1063
#define IDC_SAMEEMIT                    1063
#define IDC_SPECULARCOLOR               1064
#define IDC_DIFFUSESLIDER               1065
#define IDC_SPECULARSLIDER              1066
#define IDC_SINGLEVERTEXCHECK           1067
#define IDC_S_ALPHACKECK                1068
#define IDC_ONLYSELECTCHECK             1068
#define IDC_DISTANCESLIDER              1068
#define IDC_S_LITEDCHECK                1069
#define IDC_ATTENUATESLIDER             1069
#define IDC_S_VCOLORCHECK               1070
#define IDC_THETASLIDER                 1070
#define IDC_S_TEXTURECHECK              1071
#define IDC_PHISLIDER                   1071
#define IDC_S_GOURAUDCHECK              1072
#define IDC_ATTENUATESLIDER2            1072
#define IDC_S_BBOARDCHECK               1075
#define IDC_S_ZBIASSLIDER               1076
#define IDC_S_SINDEXSLIDER              1077
#define IDC_S_TEX1                      1078
#define IDC_S_TEX2                      1079
#define IDC_SWITCHLIST                  1079
#define IDC_S_CKEYCHECK                 1080
#define IDC_SW_ENABLE                   1081
#define IDC_S_ZBIASCHECK                1081
#define IDC_SW_ALLON                    1082
#define IDC_S_SWEMITCHECK               1082
#define IDC_SLIDER1                     1083
#define IDC_SW_SELECT                   1083
#define IDC_DOFSLIDER                   1083
#define IDC_NORMALSSLIDER               1083
#define IDC_AMBIENTSLIDER               1083
#define IDC_SW_ALLOFF                   1084
#define IDC_SW_DISABLE                  1085
#define IDC_MODELAREA                   1086
#define IDC_SW_ASSIGN                   1086
#define IDC_EXPONSEL                    1087
#define IDC_CLEARSEL                    1088
#define IDC_COLLAPSEB                   1089
#define IDC_COLLAPSET                   1090
#define IDC_REBUILDTREE                 1091
#define IDC_CUT                         1092
#define IDC_COPY                        1093
#define IDC_PASTE                       1094
#define IDC_DOFRESTORE                  1095
#define IDC_TREEALL                     1095
#define IDC_DOFRESET                    1096
#define IDC_KILL                        1096
#define IDC_YAWGROUP                    1098
#define IDC_ADDSW                       1098
#define IDC_YAWANGLE                    1100
#define IDC_PITCHGROUP                  1102
#define IDC_ROLLGROUP                   1105
#define IDC_PITCHANGLE                  1108
#define IDC_ROLLANGLE                   1109
#define IDC_DOFANGLE                    1110
#define IDC_XSPIN                       1111
#define IDC_XPOSITION                   1112
#define IDC_XPOS                        1113
#define IDC_YSPIN                       1114
#define IDC_YPOSITION                   1115
#define IDC_YPOS                        1116
#define IDC_ZSPIN                       1117
#define IDC_ZPOSITION                   1118
#define IDC_ZPOS                        1119
#define IDC_XSCALE                      1120
#define IDC_XPOS2                       1121
#define IDC_YSCALESPIN                  1122
#define IDC_YSCALE                      1123
#define IDC_YPOS2                       1124
#define IDC_DOFTYPELIST                 1125
#define IDC_ZSCALESPIN                  1126
#define IDC_ZSCALE                      1127
#define IDC_ZPOS2                       1128
#define IDC_XSCALESPIN                  1129
#define IDC_DOFINVCHECK                 1130
#define IDC_DOFLIMITS                   1131
#define IDC_DOFSCALE                    1132
#define IDC_DOFDEGREES                  1133
#define IDC_DOFMAX                      1134
#define IDC_XPOS3                       1135
#define IDC_MAXSPIN                     1136
#define IDC_DOFMIN                      1137
#define IDC_XPOS4                       1138
#define IDC_MINSPIN                     1139
#define IDC_YAWSPIN                     1140
#define IDC_DOFMOVE                     1141
#define IDC_PITCHSPIN                   1142
#define IDC_FACEMIRROR                  1142
#define IDC_CX                          1143
#define IDC_BACKFACE                    1143
#define IDC_SUNDIFFUSE                  1143
#define IDC_XPOS5                       1144
#define IDC_SELECTIONMOVE               1144
#define IDC_SUNDARK                     1144
#define IDC_CXSPIN                      1145
#define IDC_ZMAX                        1145
#define IDC_SUNMID                      1145
#define IDC_ROLLSPIN                    1146
#define IDC_ZMIN                        1146
#define IDC_SUNBRIGHT                   1146
#define IDC_SIMAX                       1147
#define IDC_SIMIN                       1148
#define IDC_ZBIASVALUE                  1149
#define IDC_SIVALUE2                    1150
#define IDC_PLANIZE                     1150
#define IDC_NORMVALUE                   1151
#define IDC_MANMOVE                     1152
#define IDC_S_XMOVE                     1153
#define IDC_S_YMOVE                     1154
#define IDC_S_ZMOVE                     1155
#define IDC_S_RELMOVE                   1156
#define IDC_MANSNAP                     1157
#define IDC_SVERTEXMOVE                 1157
#define IDC_MANSNAP2                    1158
#define IDC_SVERTEXSCALE                1158
#define IDC_GROUNDZERO                  1159
#define IDC_TEXMOVE                     1159
#define IDC_SVERTEXUV                   1159
#define IDC_S_SWNR                      1160
#define IDC_TEXSCALE                    1160
#define IDC_SVERTEXSCALEOMNI            1160
#define IDC_SPECCOLOR                   1161
#define IDC_VOFFSET                     1161
#define IDC_SVERTEXSCALEABS             1161
#define IDC_HOFFSET                     1162
#define IDC_SIVALUE4                    1162
#define IDC_Offset                      1163
#define IDC_SIVALUE5                    1163
#define IDC_VSCALE                      1164
#define IDC_S_SWMASK                    1164
#define IDC_HSCALE                      1165
#define IDC_UVCalc                      1165
#define IDC_UVCALC                      1165
#define IDC_S_PFACES                    1165
#define IDC_Offset2                     1166
#define IDC_S_PRADIUS                   1166
#define IDC_HVSCALE                     1167
#define IDC_MIRROX                      1167
#define IDC_ROTOSPIN                    1168
#define IDC_MIRROY                      1168
#define IDC_LIST1                       1169
#define IDC_MIRROZ                      1169
#define IDC_90                          1171
#define IDC_91                          1172
#define IDC_92                          1173
#define IDC_TEXSETSTEXT                 1174
#define IDC_USETEXSETNR                 1175
#define IDC_ADDTEXSET                   1176
#define IDC_DELTEXSET                   1177
#define IDC_TEXTURESELECTLIST           1177
#define IDC_ADDTEX                      1178
#define IDC_DELTEX                      1179
#define IDC_USETEX                      1180
#define IDC_ASSIGNTEX                   1181
#define IDC_LOADTEXBUTTON               1181
#define IDC_CHANGETEX                   1182
#define IDC_3DSIMPORT                   1182
#define IDC_3DSEXPORT                   1183
#define IDC_DELUNUSEDTEX                1183
#define IDC_3DSLOG                      1184
#define IDC_SELECTTEX                   1184
#define IDC_MNOSMALBUTTON               1185
#define IDC_SNORMALBUTTON               1186
#define IDC_PROGRESS1                   1186
#define IDC_BUTTON1                     1187
#define IDC_LOADPROGRESS                1188
#define IDC_X3                          1188
#define IDC_X2                          1189
#define IDC_D2                          1190
#define IDC_MaterialNr                  1190
#define IDC_D3                          1191
#define IDC_VERTEXNR                    1191
#define IDC_DCOPY                       1191
#define IDC_FACESNR                     1192
#define IDC_DPASTE                      1192
#define IDC_WARNSNR                     1193
#define IDC_SCOPY                       1193
#define IDC_ERRORNR                     1194
#define IDC_SPASTE                      1194
#define IDC_POSCOPY                     1196
#define IDC_POSPASTE                    1197
#define IDC_FLIPU                       1197
#define IDC_COPYUV                      1198
#define IDC_LIGHTLIST                   1199
#define IDC_PASTEUV                     1199
#define IDC_OWNLITECHECK                1201
#define IDC_LITETYPE                    1202
#define IDC_OTHERLITECHECK              1203
#define IDC_DIFFUSELITE                 1204
#define IDC_DISTANCETEXT                1205
#define IDC_LIGHTMOVE                   1206
#define IDC_LITESWITCHNR                1207
#define IDC_ATTENUATETEXT               1208
#define IDC_THETATETEXT                 1209
#define IDC_PHYTEXT                     1210
#define IDC_LITEADD                     1211
#define IDC_LITEKILL                    1212
#define IDC_ATTENUATETEXT2              1213
#define IDC_OSTATICLITECHECK            1214
#define IDC_RNDLITECHECK                1215
#define IDC_DOFDIMLITECHECK             1216
#define IDC_LITECOPY                    1217
#define IDC_LITEPASTE                   1218
#define IDC_LITESWITCHMASK              1219
#define IDC_CALCSTATIC                  1220
#define IDC_CALCSTATIC2                 1221
#define IDC_CLRSTATIC                   1221
#define IDC_SAVESET                     1222
#define IDC_LOADSET                     1223
#define IDC_STATICRECALC                1224
#define IDC_KILLALLLITES                1225
#define IDC_TEXSAVE                     1225
#define IDC_TEXLOAD                     1226
#define IDC_PCIRCLE                     1227
#define IDC_TEXREF                      1228
#define IDC_CHECK1                      1228
#define IDC_MIRROCHECK                  1228
#define IDC_TEXLCALC                    1229
#define IDC_SCALEXVALUE                 1229
#define IDC_SCALEYVALUE                 1230
#define IDC_SCALEZVALUE                 1231
#define IDC_SCALEXUP                    1233
#define IDC_SCALEXDN                    1236
#define IDC_SCALEYUP                    1237
#define IDC_SCALEYDN                    1238
#define IDC_SCALEZUP                    1239
#define IDC_SCALEZDN                    1240
#define ID_APP_PLANE                    32771
#define IDD_LEFT                        32772
#define IDD_UP                          32773
#define IDD_DN                          32774
#define IDD_RIGHT                       32775
#define IDD_IN                          32776
#define IDD_OUT                         32777
#define ID_INFO                         32778
#define IDC_CULLKEY                     32779
#define ID_BUTTON32780                  32780
#define ID_DOFMOVE                      32781
#define IDD_MULTI                       32783
#define IDD_ZBIAS                       32784
#define IDD_COLORKEY                    32786
#define ID_VBKEY                        32787
#define ID_DXKEY                        32788
#define ID_M1                           32789
#define ID_M2                           32790
#define ID_M3                           32791
#define ID_M4                           32792
#define ID_M5                           32793
#define ID_M6                           32794
#define ID_M7                           32795
#define ID_M8                           32796
#define ID_V1                           32797
#define ID_V2                           32798
#define ID_V3                           32799
#define ID_V4                           32800
#define ID_V5                           32801
#define ID_V6                           32802
#define ID_V7                           32803
#define ID_V8                           32804
#define ID_RESETPOS                     32805
#define ID_RESETANGLES                  32806
#define ID_SETREFERENCE                 32807
#define ID_XPLANE                       32808
#define ID_YPLANE                       32810
#define ID_ZPLANE                       32811
#define ID_3DTOGGLE                     32812
#define ID_GRIDTOGGLE                   32813
#define ID_OPTIONS_GRIDSIZE             32814
#define ID_SETGRIDSIZE                  32815
#define ID_FRAMEMODE                    32817
#define ID_VERTEXMODE                   32818
#define ID_FACEMODE                     32819
#define ID_JOINTFACEMODE                32820
#define ID_OPTIONS_ENABLESCRIPT         32821
#define ID_OPTIONS_SELECTIONMODE        32822
#define ID_OPTIONS_BACKCULLING          32827
#define ID_EDIT_DISABLEHIDE             32833
#define ID_EDIT_HIDESELECTED            32835
#define ID_EDIT_CLEARSELECTION          32839
#define ID_EDIT_EDIT                    32842
#define ID_EDITSWITCHES                 32845
#define ID_EDIT_MODELTREE               32851
#define ID_EDIT_EDITVERTEX              32854
#define ID_EDIT_EDITSURFACE             32856
#define ID_TOOLS_CHANGEDOFNUMBER        32861
#define ID_TOOLS_COPYDOF                32862
#define ID_TOOLS_PASTEDOF               32863
#define ID_EDITSUN                      32864
#define ID_FILESAVE                     32865
#define ID_FILESAVEAS                   32866
#define ID_EDIT_MAKEABACKUP             32867
#define ID_EDIT_RESTOREABACKUP          32868
#define ID_OPTIONS_SNAPTOGRID           32869
#define ID_OPTIONS_SINGLEVERTEXMODE     32872
#define ID_EDIT_EDITTEXTURE             32873
#define ID_FILE_3DSTOOL                 32876
#define ID_OPTIONS_LOCKSELECTION        32877
#define ID_TOOLS_RECORDCHANGES          32878
#define ID_TOOLS_APPLYCHANGES           32879
#define ID_TOOLS_ASSIGNSPECULARITY      32880
#define ID_EDIT_EDITLIGHTS              32881
#define ID_FILE_TEXTURESFOLDER          32886
#define ID_NVGBUTTON                    32887
#define ID_EDIT_INVERSELECTION          32891
#define ID_FACESELECTION_REMOVEEMISSIVECOLOR 32894
#define ID_FACESELECTION_MAKEEMISSIVE   32897
#define ID_FACESELECTION_REMOVEZBIAS    32899
#define ID_EDIT_KILL                    32903

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32905
#define _APS_NEXT_CONTROL_VALUE         1235
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
